
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module deneme(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire[7:0] pixel_color, background_pixel_color, char_pixel_color;
wire[9:0] next_x, next_y, char_x, char2_x;
wire vga_pll, game_clk, char_hurtbox, char2_hurtbox, char_hitbox, char2_hitbox, background, menu, menu_in;

wire[3:0] char_state, char2_state;

reg vga_reset = 1'b0;
reg initialize = 1'b0;

always@(posedge vga_pll)//giving a pulse to the reset of vga driver as needed
begin
	if ((vga_reset == 0) && (initialize == 0)) 
		vga_reset <= 1'b1;
	
	else if ((vga_reset == 1) && (initialize == 0)) 
	begin
		vga_reset <= 1'b0;
		initialize <= 1'b1;
	end
	
end

//=======================================================
//  Structural coding
//=======================================================

//instantiate the 25MHz vga clock
vga_clock clock_vga
(
	.clk(CLOCK_50),
	.vga_clock(vga_pll)
);

//instantiate the 60Hz game clock
game_clk game_clock
(
.clk(vga_pll),
.stop(SW[1]),
.step(KEY[0]),
.game_clk(game_clk)
);

//instantiate character full state machine
game_fsm game
(
.clk(game_clk),
.right(~KEY[3]),
.left(~KEY[1]),
.attack(~KEY[2]),

.right2(SW[9]),
.left2(SW[7]),
.attack2(SW[8]),

.char_x(char_x),
.char_state(char_state),

.char2_x(char2_x),
.char2_state(char2_state)
);

layering layer
(
.clk(vga_pll),
.next_x(next_x),
.next_y(next_y),
	
.char_x(char_x),
.char2_x(char2_x),
	
.char_state(char_state),
.char2_state(char2_state),
	
.char_hurtbox(char_hurtbox),
.char2_hurtbox(char2_hurtbox),
	
.char_hitbox(char_hitbox),
.char2_hitbox(char2_hitbox),
	
.background(background)
);

render_menu gamemenu
(
.clk(vga_pll),
.next_x(next_x),
.next_y(next_y),
.char_state(char_state),
.char2_state(char2_state),
.menu_pixel(menu_in)
);

rendering render
(
.clk(vga_pll),

.char_hurtbox(char_hurtbox),
.char2_hurtbox(char2_hurtbox),
	
.char_hitbox(char_hitbox),
.char2_hitbox(char2_hitbox),
	
.background(background),
.menu(menu),

.pixel_color(pixel_color)
);


////renders a background
//render_background background
//(
//	.clk(vga_pll),
//	.next_x(next_x),
//	.next_y(next_y),
//	.background_pixel_color(background_pixel_color)
//);
//
////renders the character
//render_character char
//(
//	.clk(vga_pll),
//	.char_state(char_state),
//	.next_x(next_x),
//	.next_y(next_y),
//	.char_x(char_x),
//	.char_pixel_color(char_pixel_color)
//);
//
////renders the final image
//render_layering screen
//(
//	.clk(vga_pll),
//	.next_x(next_x),
//	.next_y(next_y),
//	.char_x(char_x),
//	.char_pixel_color(char_pixel_color),
//	.background_pixel_color(background_pixel_color),
//	.pixel_color(pixel_color)
//);

//vga driver module 
vga_driver draw   
( 
	.clock(vga_pll),        // 25 MHz PLL
	.reset(vga_reset),      // Active high reset, manipulated by instantiating module
	.color_in(pixel_color), // Pixel color (RRRGGGBB) for pixel being drawn
	.next_x(next_x),        // X-coordinate (range [0, 639]) of next pixel to be drawn
	.next_y(next_y),        // Y-coordinate (range [0, 479]) of next pixel to be drawn
	.hsync(VGA_HS),         // All of the connections to the VGA screen below
	.vsync(VGA_VS),
	.red(VGA_R),
	.green(VGA_G),
	.blue(VGA_B),
	.sync(VGA_SYNC_N),
	.clk(VGA_CLK),
	.blank(VGA_BLANK_N)
);

sevenseg_display display
(
.clk(game_clk),
.state(char_state),
.toggle(SW[0]),
.hex0(HEX0),
.hex1(HEX1),
.hex2(HEX2),
.hex3(HEX3),
.hex4(HEX4),
.hex5(HEX5)
);



endmodule
